[package]
name = "mule"
version = "0.1.0"
edition = "2024"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"

mule_macho = { path = "../mule-macho/" }
mule_gb = { path = "../mule-gb/" }
